[font.normal]
family = "Meslo LG M"

[font.bold]
family = "Meslo LG M"
style = "Bold"

[font.italic]
family = "Meslo LG M"
style = "Italic"

[font.bold_italic]
family = "Meslo LG M"
style = "Bold Italic"

size = 16
