import = ["~/.config/alacritty/colors.toml", "~/.config/alacritty/fonts.toml"]

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Beam"

[env]
TERM = "xterm-256color"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[window]
padding.x = 20
padding.y = 20
opacity = 0.80
blur = true
