#! /bin/sh
bspc rule -r "*"

# auto start
sxhkd &
nm-applet &
conky &
dunst &
polybar &
picom --config ~/.config/picom/picom.conf &
feh --bg-fill --randomize ~/.config/backgrounds/* &

# window styles
bspc monitor -d home web dev txt vid mus soc avion asap extra

bspc config border_width			4
bspc config window_gap				10

bspc config split_ratio				0.5
bspc config single_monocle			false
bspc config focus_follows_pointer	true
bspc config borderless_monocle		true
bspc config borderless_monocle		true
bspc config gapless_monocle			true

bspc config focused_border_color	"#29d7e2"
bspc config normal_border_color		"#3C3C3C"
bspc config presel_feedback_color "#56949f"
bspc config active_border_color		"#908caa"
bspc config focused_border_color "#9ccfd8"
bspc config normal_border_color "#6e6a86"
