#! /bin/sh
bspc rule -r "*"

# auto start
conky &
dunst &
polybar &
picom --config ~/.config/picom/picom.conf &
feh --bg-fill --randomize ~/.config/backgrounds/* &

# window styles
bspc monitor -d home web dev txt vid mus soc avion asap extra

bspc config border_width			4
bspc config window_gap				10

bspc config split_ratio				0.5
bspc config single_monocle			false
bspc config focus_follows_pointer	true
bspc config borderless_monocle		true
bspc config borderless_monocle		true
bspc config gapless_monocle			true

bspc config focused_border_color	"#29d7e2"
bspc config normal_border_color		"#3C3C3C"
bspc config presel_feedback_color "#56949f"
bspc config active_border_color		"#908caa"
bspc config focused_border_color "#9ccfd8"
bspc config normal_border_color "#6e6a86"

# apps for systray if enabled
nm-applet &
sxhkd &

#dev
bspc rule -a Code desktop="^3" follow=on

#soc
bspc rule -a Telegram-Desktop desktop="^7" follow=on
bspc rule -a Signal desktop="^7" follow=on

#mus
bspc rule -a Spotify desktop="^6" follow=on

#vid
bspc rule -a motion_recorder="^5" follow=on
